### ISSUE TITLE
Roadmap for the project

### ISSUE THREAD

**Issue by mbj36** [mbj36/vue-burger-menu#1]
Hello all,

If you wish you contribute to this project or use the library, I am creating a road map below that would give a fair idea how i would like proceed with this project

Currently the project has base setup with `slide` animation working  and it is in very early stage so APIs may change in future.

As i will release the new version with new features, APIs may change on version upgrade, there won't be any seperate docs for previous versions, all the changes would be done in readme update. 

Things needs to be done

- [ ] Work on CSS animations for next release, my next 3 target is `stack`, `reveal` and `elastic`
- [ ] Supporting Custom Icons
- [ ] Writing tests
- [ ] Improving the Code 

I am also creating github release for every version that is published on npm

npm link - https://www.npmjs.com/package/vue-burger-menu

All Ideas and suggestions are warmly welcome, you can create a new issue or reply to this comment thread.

**Comment by AleksejDix** [comment]
Can you can render 60 Frames per second to the roadmap

**Comment by mbj36** [comment]
@AleksejDix Can you elaborate a bit more ? what is your use case ?

**Comment by mritunjaygoutam12** [comment]
Have you started implementing "Stack" amination implementation ? Otherwise I wish to start.
